### PR TITLE
Fixes async task from node error

### LINKED ISSUE #215: Task.fromNodeBack is not handling cancellation
> All of the Folktale task primitives should be dealing with cancellation.

`Task.fromNodeBack` currently doesn't prevent resolving|rejecting when the task is cancelled.

### Steps to reproduce

Given:

```js
const Task = require('folktale/concurrency/task')

const delay = Task.fromNodeback((result, error, cb) =>
    setTimeout(() => cb(error ? result : null, result)), 0)
```

This works:

```js
Task.waitAll([delay(1, false), delay(2, true)])
   .orElse(e => Task.rejected(console.log('Error: ', e)))
   .run() // => Error 2
```

And this don't:

```js
Task.waitAll([delay(1, false), delay(2, true), delay(3, true)])
   .orElse(e => Task.rejected(console.log('Error: ', e)))
   .run() // => Error 2
  // throw new Error('Only pending deferreds can be ' + description + ', this deferred is already ' + description + '.');
```

#### Expected behaviour

Last example shouldn't throw an error (`Task.fromNodeback` should check if task is already cancelled).

#### Observed behaviour

The error *Only pending deferreds can be ' + description + ', this deferred is already ' + description + '.'* is thrown.

### Environment

  - OS: Vagrant Debian Box
  - JavaScript VM: node v11.6.0
  - Folktale version: 2.3.1

### Additional information

Related issue (comment): https://github.com/origamitower/folktale/issues/153#issuecomment-453110251
Related file: https://github.com/origamitower/folktale/blob/master/packages/base/source/conversions/nodeback-to-task.js#L25

### PR DESCRIPTION
**Pull request by cdoublev**
Fixes #215 

Added a test by following the given principle from the doc:

> tests should fail before applying your change, and pass after applying your change.

### CODE REVIEW

File: test/source/specs/base/concurrency/task.js [hunk 1]
```diff
@@ -575,4 +575,13 @@ describe('Data.Task', () => {
...
     });
   });
+
+    it('Returns a converted task only from the first (async) nodeback error', async () => {
+        const error = 'failed';
+        const fn = (str, cb) => setTimeout(() => cb(error, ''), 0);
+        const convertedFn = Task.fromNodeback(fn);
+        const task1 = convertedFn('test');
+        const task2 = convertedFn('test');
+        await task1.and(task2).run().promise().catch(e => $ASSERT(e === error));
```
Comment (cdoublev) [inline test/source/specs/base/concurrency/task.js]: Maybe require('assert').doesNotThrow(async () => await task1.and(task2).run().promise()) was more meaningfull... But it would seems "disconnected" from the test case description.

File: packages/base/source/conversions/nodeback-to-task.js [hunk 2]
```diff
@@ -22,7 +22,7 @@ const { task } = require('folktale/concurrency/task');
 
 const nodebackToTask = fn => (...args) => (
   task(r =>
-    fn(...args, (err, data) => err ? r.reject(err) : r.resolve(data))
+    fn(...args, (err, data) => r.isCancelled ? undefined : err ? r.reject(err) : r.resolve(data))
```
Comment (cdoublev) [inline packages/base/source/conversions/nodeback-to-task.js]: I hope the nested ternary is not too ugly, feel free to make it more verbous.

File: test/source/specs/base/concurrency/task.js [hunk 3]
```diff
@@ -574,5 +575,14 @@ describe('Data.Task', () => {
       const task = convertedFn('test');
       await task.run().promise().catch(e => $ASSERT(e === error));
     });
+
+    it('Should allow rejecting more than once', async () => {
```
Comment (cdoublev) [inline test/source/specs/base/concurrency/task.js]: Following [corresponding `future` test case](https://github.com/origamitower/folktale/blob/master/test/source/specs/base/concurrency/future.js#L72) and my [own review](https://github.com/origamitower/folktale/pull/216#discussion_r247230854).

```js
it('shouldnt allow resolving more than once', ...)
```
